const LOADING_ITEM_DATA = 'LOADING_ITEM_DATA';
const LOADING_ITEM_DATA_SUCCESS = 'LOADING_ITEM_DATA_SUCCESS';
const LOADING_ITEM_DATA_FAILED = 'LOADING_ITEM_DATA_FAILED';

export {LOADING_ITEM_DATA, LOADING_ITEM_DATA_FAILED, LOADING_ITEM_DATA_SUCCESS};